import type {EditorThemeClasses} from 'lexical';

import './DefaultTheme.css';

const theme: EditorThemeClasses = {
  autocomplete: 'LexiformTheme__autocomplete',
  blockCursor: 'LexiformTheme__blockCursor',
  characterLimit: 'LexiformTheme__characterLimit',
  code: 'LexiformTheme__code',
  codeHighlight: {
    atrule: 'LexiformTheme__tokenAttr',
    attr: 'LexiformTheme__tokenAttr',
    boolean: 'LexiformTheme__tokenProperty',
    builtin: 'LexiformTheme__tokenSelector',
    cdata: 'LexiformTheme__tokenComment',
    char: 'LexiformTheme__tokenSelector',
    class: 'LexiformTheme__tokenFunction',
    'class-name': 'LexiformTheme__tokenFunction',
    comment: 'LexiformTheme__tokenComment',
    constant: 'LexiformTheme__tokenProperty',
    deleted: 'LexiformTheme__tokenProperty',
    doctype: 'LexiformTheme__tokenComment',
    entity: 'LexiformTheme__tokenOperator',
    function: 'LexiformTheme__tokenFunction',
    important: 'LexiformTheme__tokenVariable',
    inserted: 'LexiformTheme__tokenSelector',
    keyword: 'LexiformTheme__tokenAttr',
    namespace: 'LexiformTheme__tokenVariable',
    number: 'LexiformTheme__tokenProperty',
    operator: 'LexiformTheme__tokenOperator',
    prolog: 'LexiformTheme__tokenComment',
    property: 'LexiformTheme__tokenProperty',
    punctuation: 'LexiformTheme__tokenPunctuation',
    regex: 'LexiformTheme__tokenVariable',
    selector: 'LexiformTheme__tokenSelector',
    string: 'LexiformTheme__tokenSelector',
    symbol: 'LexiformTheme__tokenProperty',
    tag: 'LexiformTheme__tokenProperty',
    url: 'LexiformTheme__tokenOperator',
    variable: 'LexiformTheme__tokenVariable',
  },
  embedBlock: {
    base: 'LexiformTheme__embedBlock',
    focus: 'LexiformTheme__embedBlockFocus',
  },
  hashtag: 'LexiformTheme__hashtag',
  heading: {
    h1: 'LexiformTheme__h1',
    h2: 'LexiformTheme__h2',
    h3: 'LexiformTheme__h3',
    h4: 'LexiformTheme__h4',
    h5: 'LexiformTheme__h5',
    h6: 'LexiformTheme__h6',
  },
  hr: 'LexiformTheme__hr',
  hrSelected: 'LexiformTheme__hrSelected',
  indent: 'LexiformTheme__indent',
  link: 'LexiformTheme__link',
  list: {
    checklist: 'LexiformTheme__checklist',
    listitem: 'LexiformTheme__listItem',
    listitemChecked: 'LexiformTheme__listItemChecked',
    listitemUnchecked: 'LexiformTheme__listItemUnchecked',
    nested: {
      listitem: 'LexiformTheme__nestedListItem',
    },
    olDepth: [
      'LexiformTheme__ol1',
      'LexiformTheme__ol2',
      'LexiformTheme__ol3',
      'LexiformTheme__ol4',
      'LexiformTheme__ol5',
    ],
    ul: 'LexiformTheme__ul',
  },
  ltr: 'LexiformTheme__ltr',
  mark: 'LexiformTheme__mark',
  markOverlap: 'LexiformTheme__markOverlap',
  paragraph: 'LexiformTheme__paragraph',
  quote: 'LexiformTheme__quote',
  rtl: 'LexiformTheme__rtl',
  specialText: 'LexiformTheme__specialText',
  tab: 'LexiformTheme__tabNode',
  text: {
    bold: 'LexiformTheme__textBold',
    capitalize: 'LexiformTheme__textCapitalize',
    code: 'LexiformTheme__textCode',
    highlight: 'LexiformTheme__textHighlight',
    italic: 'LexiformTheme__textItalic',
    lowercase: 'LexiformTheme__textLowercase',
    strikethrough: 'LexiformTheme__textStrikethrough',
    subscript: 'LexiformTheme__textSubscript',
    superscript: 'LexiformTheme__textSuperscript',
    underline: 'LexiformTheme__textUnderline',
    underlineStrikethrough: 'LexiformTheme__textUnderlineStrikethrough',
    uppercase: 'LexiformTheme__textUppercase',
  },
};

export default theme;
